# Generated by Django 4.2 on 2023-05-30 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_userprofile_profile_image'),
        ('users', '0002_bookingcancellationrequest_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingcancellationrequest',
            name='theatre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.userprofile'),
        ),
    ]
