# Generated by Django 4.2 on 2023-05-30 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_bookingcancellationrequest_theatre'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingcancellationrequest',
            name='user',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
