# Generated by Django 4.2 on 2023-05-06 14:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("theatre", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="is_theatre_owner",
            new_name="is_theatre",
        ),
    ]
