# Generated by Django 4.2 on 2023-05-09 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0005_remove_theatre_userprofile_theatre_is_theatre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screen',
            name='theatre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theatre.theatre'),
        ),
    ]
