# Generated by Django 4.2 on 2023-05-09 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("admin_dashboard", "0005_alter_movies_image"),
        ("theatre", "0007_alter_screen_theatre"),
    ]

    operations = [
        migrations.AlterField(
            model_name="screen",
            name="movies",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="admin_dashboard.movies"
            ),
        ),
        migrations.AlterField(
            model_name="screen",
            name="theatre",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="theatre.theatre"
            ),
        ),
    ]
