# Generated by Django 3.2.9 on 2023-05-12 06:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("theatre", "0013_alter_screen_price2_alter_screen_price3"),
    ]

    operations = [
        migrations.AlterField(
            model_name="screen",
            name="price2",
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name="screen",
            name="price3",
            field=models.IntegerField(blank=True, default=None),
        ),
    ]
