# Generated by Django 3.2.9 on 2023-05-12 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0014_auto_20230512_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screen',
            name='price2',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='screen',
            name='price3',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
