# Generated by Django 3.2.9 on 2023-05-12 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0015_auto_20230512_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screen',
            name='price1',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='screen',
            name='price2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='screen',
            name='price3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
    ]
