# Generated by Django 4.2 on 2023-05-18 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("theatre", "0018_alter_screen_price1_alter_screen_price2_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Show_Time",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.TimeField()),
            ],
        ),
        migrations.AddField(
            model_name="screen",
            name="show_times",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="theatre.show_time",
            ),
        ),
    ]
