# Generated by Django 4.2 on 2023-05-18 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0020_alter_screen_show_times'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screen',
            name='show_times',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='theatre.show_time'),
        ),
    ]
