# Generated by Django 4.2 on 2023-05-18 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0024_alter_screen_show_times'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screen',
            name='show_times',
        ),
        migrations.DeleteModel(
            name='Show_Time',
        ),
    ]
