# Generated by Django 4.2 on 2023-05-20 06:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("theatre", "0031_alter_screen_total_seat_columns_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="screen",
            name="total_seat_columns",
        ),
        migrations.RemoveField(
            model_name="screen",
            name="total_seat_rows",
        ),
        migrations.RemoveField(
            model_name="screen",
            name="unavailable_seats",
        ),
    ]
