# Generated by Django 4.2 on 2023-05-22 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0036_remove_screen_unavailable_seats_bookedseat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookedseat',
            name='date',
            field=models.CharField(max_length=20),
        ),
    ]
