# Generated by Django 4.2 on 2023-05-22 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0037_alter_bookedseat_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookedseat',
            name='time',
            field=models.CharField(default='', max_length=255),
        ),
    ]
