# Generated by Django 4.2 on 2023-05-27 05:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("theatre", "0038_bookedseat_time"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BookedSeat",
        ),
    ]
