# Generated by Django 4.2 on 2023-05-27 07:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("theatre", "0040_bookedseat"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookedseat",
            name="movie",
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name="bookedseat",
            name="price",
            field=models.IntegerField(default=None),
        ),
    ]
