# Generated by Django 4.2 on 2023-05-27 12:43

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    dependencies = [
        ("theatre", "0041_bookedseat_movie_bookedseat_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookedseat",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                default=None, max_length=128, null=True, region=None
            ),
        ),
    ]
