# Generated by Django 4.2 on 2023-05-28 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0042_alter_bookedseat_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookedseat',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
