# Generated by Django 4.2 on 2023-06-05 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0044_bookedseat_movie_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookedseat',
            name='payment_order_id',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='bookedseat',
            name='payment_id',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
