# Generated by Django 4.2 on 2023-06-05 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0046_alter_bookedseat_payment_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theatre_Sale_Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('earnings', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('status', models.CharField(max_length=255)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theatre.bookedseat')),
            ],
        ),
    ]
