# Generated by Django 4.2 on 2023-06-05 14:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("theatre", "0048_remove_theatre_sale_report_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="theatre_sale_report",
            name="theatre",
        ),
        migrations.AddField(
            model_name="theatre_sale_report",
            name="name",
            field=models.CharField(default=None, max_length=255),
        ),
    ]
