# Generated by Django 4.2 on 2023-05-06 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("admin_dashboard", "0002_alter_movies_comments_alter_movies_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movies",
            name="comments",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="admin_dashboard.all_comments",
            ),
        ),
        migrations.AlterField(
            model_name="movies",
            name="rating",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=3, null=True
            ),
        ),
    ]
