# Generated by Django 4.2 on 2023-06-13 13:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "admin_dashboard",
            "0007_alter_movies_description_alter_movies_genre_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movies",
            name="comments",
        ),
        migrations.RemoveField(
            model_name="movies",
            name="rating",
        ),
        migrations.AddField(
            model_name="movies",
            name="cast",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="movies",
            name="director",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="movies",
            name="writers",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name="All_Comments",
        ),
    ]
