# Generated by Django 4.2 on 2023-06-13 13:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "admin_dashboard",
            "0008_remove_movies_comments_remove_movies_rating_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="movies",
            name="year",
            field=models.IntegerField(null=True),
        ),
    ]
